@PrimeApi_HostAddress = http://localhost:5247

GET {{PrimeApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{PrimeApi_HostAddress}}/api/Users/GetByUsernamePassword
Accept: application/json
Accept-Language: en-US
Content-Type: application/json

{
    "Username": "jdoe",
    "Password": "changeme123"
}